### ISSUE TITLE
Discord update

### ISSUE THREAD

**Issue by AutisticSniper** [rkhous/Discord-Prune-Aid#1]
Hi! I believe that discord updated stuff hence giving me errors when trying to run your bot. I have tried to no avail in finding out what's wrong (I am not good in coding).

This is what I get when launching it:
Ignoring exception in on_ready
Traceback (most recent call last):
  File "\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "\Desktop\Bot\bot.py", line 14, in on_ready
    server = bot.get_server(server_id)
AttributeError: 'Bot' object has no attribute 'get_server'

When doing =checklist I get this:

Ignoring exception in command checklist:
Traceback (most recent call last):
  File "\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "\Desktop\Bot\bot.py", line 38, in checklist
    await bot.say("You are not an admin of this bot.")
AttributeError: 'Bot' object has no attribute 'say'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'say'

**Comment by rkhous** [comment]
Hi, 

Please let me know what version of Python you're running, what version of the discord API you're running, and your operating system.

**Comment by AutisticSniper** [comment]
> Hi,
> 
> Please let me know what version of Python you're running, what version of the discord API you're running, and your operating system.

Python 3.6 (tried with the latest as well, 3.8).
Discord.py is 1.2.5 I believe.

Windows 10 Pro 64-bit

**Comment by AutisticSniper** [comment]
I believe this is the issue:
https://discordpy.readthedocs.io/en/latest/migrating.html

I am having trouble updating all of  the code though.

**Comment by rkhous** [comment]
I will take a look at it this weekend and give you an update.

**Comment by AutisticSniper** [comment]
Anything? Or is it on my end, something I've been doing wrong? Maybe you can point me to which version of python/discord api etc I have to be using to use the "old" format? So you don't have to re-write anything.

**Comment by rkhous** [comment]
I can confirm I'm having no issues using 0.16.12 of discord.py on Python 3.6

Please create a venv, and install 0.16.12 of discord.py. 
Also make sure to use Python 3.6

If that works out for you, let me know and then close the issue :)
I'll update it with notes so others can avoid the issue.

**Comment by AutisticSniper** [comment]
Instantly worked with discord.py version of 0.16.12 instead of 1.2.5 (newest). Thank you.

**Comment by AutisticSniper** [comment]
Instantly worked with discord.py version of 0.16.12 instead of 1.2.5 (newest). Thank you. However it creates a "logs" file where I get "FORBIDDEN (status code: 403): Missing Permissions" when I try to do =delete. =checklist works fine.

Edit: Fixed, had to do with the Prune Bot's role.

Edit 2: Also, thank you for making this. I was searching so for long for something similar to this, it was such a headache when you have a server that auto-assigns roles upon join and you can't prune them (can't prune those who have roles).

**Comment by rkhous** [comment]
Absolutely!
Glad you found it and it helped you out! :)
